M48
; DRILL file {KiCad (6.0.5)} date Fri Feb 24 20:57:03 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-24T20:57:03-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1299
%
G90
G05
T1
X12.6198Y-4.3977
X12.6198Y-5.3819
X12.6198Y-5.6477
X12.6198Y-6.6319
T0
M30
